version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/FixIT/react-front-end

    steps:
      - checkout:
          path: ~/FixIT
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - cypress/run:
            start: npm start
            wait-on: 'https://fix-it-backend.herokuapp.com/'
            working_directory: react-front-end
  deploy:
    machine:
      enabled: true

    working_directory: ~/FixIT

    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:c6:9e:81:51:b5:a8:6f:bc:d7:53:ab:b6:fc:eb:82"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/hanuz06/FixIT.git master:production

workflows:
  test_and_deploy:
    jobs:
      # - cypress/run:
      #     start: npm start
      #     wait-on: 'https://fix-it-backend.herokuapp.com/'
      #     working_directory: react-front-end
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
            - cypress/run