version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/FixIT/react-front-end

    steps:
      - checkout:
          path: ~/FixIT
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  build:
    jobs:
      - cypress/run:
        start: npm start
        wait-on: 'https://fix-it-backend.herokuapp.com/'