version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/FixIT/react-front-end

    steps:
      - checkout:
          path: ~/FixIT
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - build